name: nisitku_lite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  logger: ^2.4.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
  - family: Kanit
    fonts:
      - asset: assets/fonts/Kanit-Regular.ttf
      - asset: assets/fonts/Kanit-Italic.ttf
        style: italic
      - asset: assets/fonts/Kanit-Bold.ttf
        weight: 700
      - asset: assets/fonts/Kanit-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Kanit-Light.ttf
        weight: 300
      - asset: assets/fonts/Kanit-LightItalic.ttf
        weight: 300
        style: italic
